image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm ci
  - BASE_URL=${BASE_URL} >> .env
  - npm run build
  - rm -fR ./public
  - mv ./dist ./public

  artifacts:
    paths:
    - public
    - .env
  
  only:
  - master
